version:             "3.6"
services:
  rutorrent:
    image:           linuxserver/rutorrent
    container_name:  rutorrent
    restart:         always
    network_mode:    ${RUTORRENT_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/rutorrent:/config
      - ${DOWNLOADSDIR}:/downloads
