services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/rutorrent:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/downloads
