version:             "3.6"
services:
  muximux:
    image:           lsiocommunity/muximux
    container_name:  muximux
    restart:         always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/muximux:/config
