version:             "3.6"
services:
  sickrage:
    image:           linuxserver/sickrage
    container_name:  sickrage
    restart:         always
    network_mode:    ${SICKRAGE_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/sickrage:/config
      - ${DOWNLOADSDIR}:/downloads
      - ${MEDIADIR_TV}:/tv
