services:
  sickrage:
    image: linuxserver/sickrage
    container_name: sickrage
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sickrage:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/data
      - ${DOWNLOADSDIR}:/downloads
      - ${MEDIADIR_TV}:/tv
