version:             "3.6"
services:
  unifi:
    image:           linuxserver/unifi
    container_name:  unifi
    restart:         always
    network_mode:    ${UNIFI_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/unifi:/config
