services:
  unifi:
    image:           linuxserver/unifi
    container_name:  unifi
    restart:         unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/unifi:/config
      - ${DOCKERSHAREDDIR}:/shared
