version:             "3.6"
services:
  organizr:
    image:           lsiocommunity/organizr
    container_name:  organizr
    restart:         always
    network_mode:    ${ORGANIZR_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/organizr:/config
