services:
  organizr:
    image:           tronyx/docker-organizr-v2:php-fpm
    container_name:  organizr
    restart:         always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/organizr:/config
      - ${DOCKERSHAREDDIR}:/shared
