version:             "3.6"
services:
  plexrequests:
    image:           linuxserver/plexrequests
    container_name:  plexrequests
    restart:         always
    network_mode:    ${PLEXREQUESTS_NETWORK_MODE}
    environment:
      - URL_BASE=/plexrequests
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/plexrequests:/config
