services:
  bazarr:
    image:           linuxserver/bazarr
    container_name:  bazarr
    restart:         unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${MEDIADIR_MOVIES}:/movies
      - ${MEDIADIR_TV}:/tv
