version:             "3.6"
services:
  jackett:
    image:           linuxserver/jackett
    container_name:  jackett
    restart:         always
    network_mode:    ${JACKETT_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/jackett:/config
      - ${DOWNLOADSDIR}:/downloads
