services:
  nextcloud:
    image:           linuxserver/nextcloud
    container_name:  nextcloud
    restart:         unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/nextcloud:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${NEXTCLOUD_DATADIR}:/data
