version:             "3.6"
services:
  duckdns:
    image:           linuxserver/duckdns
    container_name:  duckdns
    restart:         always
    network_mode:    ${DUCKDNS_NETWORK_MODE}
    environment:
      - LOG_FILE=${DUCKDNS_LOG_FILE}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/duckdns:/config
