version:             "3.6"
services:
  lazylibrarian:
    image:           linuxserver/lazylibrarian
    container_name:  lazylibrarian
    restart:         always
    network_mode:    ${LAZYLIBRARIAN_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/lazylibrarian:/config
      - ${DOWNLOADSDIR}:/downloads
      - ${MEDIADIR_BOOKS}:/books
