version:             "3.6"
services:
  transmission:
    image:           linuxserver/transmission
    container_name:  transmission
    restart:         always
    network_mode:    ${TRANSMISSION_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/transmission:/config
      - ${DOWNLOADSDIR}:/downloads
      - ${DOWNLOADSDIR}/watch:/watch
