version:             "3.6"
services:
  ombi:
    image:           linuxserver/ombi
    container_name:  ombi
    restart:         always
    network_mode:    ${OMBI_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/ombi:/config
