version:             "3.6"
services:
  portainer:
    image:           portainer/portainer
    container_name:  portainer
    restart:         always
    network_mode:    ${PORTAINER_NETWORK_MODE}
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFDIR}/portainer:/data
    command:         -H unix:///var/run/docker.sock
