services:
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${MEDIADIR_MOVIES}:/data/movies
      - ${MEDIADIR_MUSIC}:/data/music
      - ${MEDIADIR_TV}:/data/tv
      - ${PLEX_TRANSCODEDIR}:/transcode
