version:             "3.6"
services:
  monitorr:
    image:           monitorr/monitorr
    container_name:  monitorr
    restart:         always
    network_mode:    ${MONITORR_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/monitorr:/app
