services:
  htpcmanager:
    image: linuxserver/htpcmanager
    container_name: htpcmanager
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/htpcmanager:/config
      - ${DOCKERSHAREDDIR}:/shared
