services:
  homeassistant:
    image:           homeassistant/home-assistant
    container_name:  homeassistant
    restart:         unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/homeassistant:/config
      - ${DOCKERSHAREDDIR}:/shared
