version:             "3.6"
services:
  homeassistant:
    image:           homeassistant/home-assistant
    container_name:  home-assistant
    restart:         always
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/homeassistant:/config
