services:
  calibreweb:
    image:           linuxserver/calibre-web
    container_name:  calibreweb
    restart:         always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/calibreweb:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${MEDIADIR_BOOKS}:/books
