version:             "3.6"
services:
  nzbget:
    image:           linuxserver/nzbget
    container_name:  nzbget
    restart:         always
    network_mode:    ${NZBGET_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/nzbget:/config
      - ${DOWNLOADSDIR}:/downloads
