version:             "3.6"
services:
  syncthing:
    image:           linuxserver/syncthing
    container_name:  syncthing
    restart:         always
    network_mode:    ${SYNCTHING_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/syncthing:/config
      - ${SYNCTHING_SOURCEDIR}:/source
