version:             "3.6"
services:
  headphones:
    image:           linuxserver/headphones
    container_name:  headphones
    restart:         always
    network_mode:    ${HEADPHONES_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/headphones:/config
      - ${DOWNLOADSDIR}:/downloads
      - ${MEDIADIR_MUSIC}:/music
