services:
  thelounge:
    image:           linuxserver/thelounge
    container_name:  thelounge
    restart:         always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/thelounge:/config
      - ${DOCKERSHAREDDIR}:/shared
