services:
  guacamole:
    image:           oznu/guacamole
    container_name:  guacamole
    restart:         unless-stopped
    environment:
      - EXTENSIONS=${GUACAMOLE_EXTENSIONS}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/guacamole:/config
      - ${DOCKERSHAREDDIR}:/shared
