version:             "3.6"
services:
  deluge:
    image:           linuxserver/deluge
    container_name:  deluge
    restart:         always
    network_mode:    ${DELUGE_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/deluge:/config
      - ${DOWNLOADSDIR}:/downloads
