services:
  deluge:
    image:           linuxserver/deluge
    container_name:  deluge
    restart:         unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/deluge:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/downloads
