version:             "3.6"
services:
  duplicati:
    image:           linuxserver/duplicati
    container_name:  duplicati
    restart:         always
    network_mode:    ${DUPLICATI_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/duplicati:/config
      - ${DUPLICATI_BACKUPSDIR}:/backups
      - ${DUPLICATI_SOURCEDIR}:/source
