version:             "3.6"
services:
  tautulli:
    image:           linuxserver/tautulli
    container_name:  tautulli
    restart:         always
    network_mode:    ${TAUTULLI_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/tautulli:/config
      - ${DOCKERCONFDIR}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
