version:             "3.6"
services:
  plex:
    image:           plexinc/pms-docker:${PLEX_TAG}
    container_name:  plex
    hostname:        plex
    restart:         always
    environment:
      - ADVERTISE_IP="http://${PLEX_IP}:${PLEX_PORT_32400}/"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_GID=${PGID}
      - PLEX_UID=${PUID}
      - TZ=${TZ}
    ports:
      - "${PLEX_PORT_1900}:1900/udp"
      - "${PLEX_PORT_3005}:3005/tcp"
      - "${PLEX_PORT_32400}:32400/tcp"
      - "${PLEX_PORT_32410}:32410/udp"
      - "${PLEX_PORT_32412}:32412/udp"
      - "${PLEX_PORT_32413}:32413/udp"
      - "${PLEX_PORT_32414}:32414/udp"
      - "${PLEX_PORT_32469}:32469/tcp"
      - "${PLEX_PORT_8324}:8324/tcp"
    volumes:
      - ${DOCKERCONFDIR}/plex:/config
      - ${MEDIADIR_MOVIES}:/data/movies
      - ${MEDIADIR_MUSIC}:/data/music
      - ${MEDIADIR_TV}:/data/tv
      - ${PLEX_TRANSCODEDIR}:/transcode
