version:             "3.6"
services:
  tautulli:
    image:           linuxserver/tautulli
    container_name:  tautulli
    hostname:        tautulli
    restart:         always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - "${TAUTULLI_PORT_8181}:8181"
    volumes:
      - ${DOCKERCONFDIR}/tautulli:/config
      #- ${DOCKERCONFDIR}/tautulli/logs:/logs:ro
