version:             "3.6"
services:
  lidarr:
    image:           linuxserver/lidarr
    container_name:  lidarr
    restart:         always
    network_mode:    ${LIDARR_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/lidarr:/config
      - ${DOWNLOADSDIR}:/downloads
      - ${MEDIADIR_MUSIC}:/music
