version:             "3.6"
services:
  hydra2:
    image:           linuxserver/hydra2
    container_name:  hydra2
    restart:         always
    network_mode:    ${HYDRA2_NETWORK_MODE}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/hydra2:/config
      - ${DOWNLOADSDIR}:/downloads
